# Generated by Django 4.0.3 on 2022-06-27 03:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Amenities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amenities_name', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='availability_date',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.TimeField()),
                ('end_date', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='images',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_image', models.ImageField(upload_to='images/')),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('address', models.CharField(max_length=300)),
                ('location', models.CharField(max_length=300)),
                ('phone', models.TextField()),
                ('link', models.CharField(max_length=600)),
                ('about', models.TextField()),
                ('price', models.FloatField()),
                ('vendor_id', models.CharField(max_length=10)),
                ('rate', models.TextField(max_length=10)),
                ('size', models.IntegerField(default=100, max_length=10)),
                ('amenities', models.ManyToManyField(to='Items.amenities')),
                ('availability_date', models.ManyToManyField(to='Items.availability_date')),
                ('images', models.ManyToManyField(to='Items.images')),
            ],
        ),
        migrations.CreateModel(
            name='ItemType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_name', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='resevedTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=False)),
                ('Date', models.DateTimeField()),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.event')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Items.item')),
                ('time', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Items.availability_date')),
            ],
        ),
        migrations.AddField(
            model_name='item',
            name='types',
            field=models.ManyToManyField(to='Items.itemtype'),
        ),
    ]
